linters:
  enable-all: true
  disable:
    - testpackage
    - exhaustivestruct
    - exhaustruct
    - paralleltest
    - interfacer
    - scopelint
    - maligned
    - golint
    - nolintlint
    - lll
    - gofmt
linter-settings:
  misspell:
    locale: en_GB
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - dupl
        - funlen


