linters:
  enable-all: true
  disable:
    - testpackage
    - exhaustivestruct
    - exhaustruct
    - paralleltest
    - interfacer
    - scopelint
    - maligned
    - golint
linter-settings:
  misspell:
    locale: en_GB
