# !! Requires Pre-Commit
# !!    https://pre-commit.com
# !! Config File: $GIT_REPO_ROOT/.pre-commit-config.yaml
# !! Already have a config file present?
# !!    Copy/Paste everything below `repos:` into your existing file
# !! Don't already have a config file?
# !!    Copy this whole file into your repo root (as '.pre-commit-config.yaml')
# !!    Delete this header section
# !!    Consider adding some built-in pre-commmit hooks to your project
# !!    (They're quite useful!)
# !! ALL Hooks enabled by default - Comment out hooks you are not using
repos:
-   repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-beta.5
    hooks:
    #
    # Go Build
    #
    -   id: go-build-mod
    #
    # Go Mod Tidy
    #
    -   id: go-mod-tidy
    -   id: go-mod-tidy-repo
    #
    # Go Test
    #
    -   id: go-test-mod
    # -   id: go-test-pkg
    -   id: go-test-repo-mod
    # -   id: go-test-repo-pkg
    #
    # Go Vet
    #
    -   id: go-vet-mod
    #
    # GolangCI-Lint
    # - Fast Multi-Linter
    # - Can be configured to replace MOST other hooks
    # - Supports repo config file for configuration
    # - https://github.com/golangci/golangci-lint
    #
    -   id: golangci-lint-mod
